# Inspired in: https://stackoverflow.com/a/52770084
backend:
  name: github
  repo: respinha/React-Landing-Page-Template

media_folder: "public/img"
public_folder: "/public/img"

collections:
  - name: projects
    label: Projects
    folder: public/_posts  
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      # fields:
      #   - name: name
      #     label: 'Name'
      #     widget: string
      #     required: true
      #   - name: description
      #     label: 'Description'
      #     widget: string
      #     required: true
      #   - name: date
      #     label: 'Date'
      #     widget: date
      #     required: true
        